import { AppSpec, PageSpec, ComponentSpec } from '@omniforge/shared';

export class FrontendAgent {
  private huggingFaceService: any;

  constructor(huggingFaceService?: any) {
    this.huggingFaceService = huggingFaceService;
  }

  /**
   * Generates comprehensive Next.js frontend code with Hugging Face assistance
   */
  async generateFrontend(spec: AppSpec): Promise<{ files: Array<{ path: string; content: string }> }> {
    const files: Array<{ path: string; content: string }> = [];

    // Generate layout (await is not needed here as it's synchronous)
    files.push(this.generateLayout());

    // Generate pages
    for (const page of spec.pages || []) {
      const pageContent = await this.generatePageComponent(page);
      files.push(this.generatePage(page, pageContent));
      files.push(this.generatePageMetadata(page));
    }

    // Generate shared components
    files.push(...this.generateSharedComponents());

    // Generate hooks
    files.push(...this.generateHooks());

    // Generate utilities
    files.push(...this.generateUtilities());

    // Generate API client
    files.push(this.generateAPIClient(spec.apis || []));

    // Generate package.json
    files.push(this.generatePackageJson());

    // Generate next.config.js
    files.push(this.generateNextConfig());

    // Generate tailwind.config.js
    files.push(this.generateTailwindConfig(spec.ui));

    return { files };
  }

  private generateLayout(): { path: string; content: string } {
    return {
      path: 'app/layout.tsx',
      content: `import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'OmniForge Generated App',
  description: 'Generated by OmniForge',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`,
    };
  }

  private generatePage(page: PageSpec, content?: string): { path: string; content: string } {
    const componentName = this.toPascalCase(page.name);
    const components = page.components || [];

    // Use generated content if available, otherwise fallback
    if (content) {
      return {
        path: `app${page.path === '/' ? '' : page.path}/page.tsx`,
        content,
      };
    }

    return {
      path: `app${page.path === '/' ? '' : page.path}/page.tsx`,
      content: `'use client';

import { useEffect, useState } from 'react';

export default function ${componentName}Page() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // TODO: Fetch page data
    setLoading(false);
  }, []);

  if (loading) {
    return <div className="flex items-center justify-center min-h-screen">Loading...</div>;
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow-sm border-b">
        <div className="container mx-auto px-4 py-4">
          <h1 className="text-2xl font-bold text-gray-900">${page.name}</h1>
        </div>
      </header>
      <main className="container mx-auto px-4 py-8">
        ${components.map((c, i) => this.generateComponentCode(c, i)).join('\n        ')}
      </main>
    </div>
  );
}
`,
    };
  }

  private generatePageMetadata(page: PageSpec): { path: string; content: string } {
    return {
      path: `app${page.path === '/' ? '' : page.path}/metadata.ts`,
      content: `import { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${page.name}',
  description: '${page.name} page',
};
`,
    };
  }

  private generateComponentCode(component: ComponentSpec, index: number): string {
    return `<div key="${index}" className="mb-4">
      {/* ${component.type} component */}
    </div>`;
  }

  private generateSharedComponents(): Array<{ path: string; content: string }> {
    return [
      {
        path: 'components/ui/Button.tsx',
        content: `interface ButtonProps {
  children: React.ReactNode;
  onClick?: () => void;
  variant?: 'primary' | 'secondary' | 'outline';
  disabled?: boolean;
}

export function Button({ children, onClick, variant = 'primary', disabled }: ButtonProps) {
  const baseStyles = 'px-4 py-2 rounded-lg font-medium transition-colors';
  const variants = {
    primary: 'bg-blue-600 text-white hover:bg-blue-700',
    secondary: 'bg-gray-200 text-gray-900 hover:bg-gray-300',
    outline: 'border border-gray-300 text-gray-700 hover:bg-gray-50',
  };

  return (
    <button
      className={\`\${baseStyles} \${variants[variant]} \${disabled ? 'opacity-50 cursor-not-allowed' : ''}\`}
      onClick={onClick}
      disabled={disabled}
    >
      {children}
    </button>
  );
}
`,
      },
      {
        path: 'components/ui/Card.tsx',
        content: `interface CardProps {
  children: React.ReactNode;
  className?: string;
}

export function Card({ children, className = '' }: CardProps) {
  return (
    <div className={\`bg-white rounded-xl shadow-sm border border-gray-200 p-6 \${className}\`}>
      {children}
    </div>
  );
}
`,
      },
      {
        path: 'components/ui/Input.tsx',
        content: `interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
}

export function Input({ label, error, className = '', ...props }: InputProps) {
  return (
    <div className="w-full">
      {label && <label className="block text-sm font-medium text-gray-700 mb-1">{label}</label>}
      <input
        className={\`w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 \${error ? 'border-red-500' : 'border-gray-300'} \${className}\`}
        {...props}
      />
      {error && <p className="mt-1 text-sm text-red-600">{error}</p>}
    </div>
  );
}
`,
      },
    ];
  }

  private generateHooks(): Array<{ path: string; content: string }> {
    return [
      {
        path: 'hooks/useApi.ts',
        content: `import { useState, useEffect } from 'react';

export function useApi<T>(url: string) {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch(url)
      .then((res) => res.json())
      .then((data) => {
        setData(data);
        setLoading(false);
      })
      .catch((err) => {
        setError(err.message);
        setLoading(false);
      });
  }, [url]);

  return { data, loading, error };
}
`,
      },
    ];
  }

  private generateUtilities(): Array<{ path: string; content: string }> {
    return [
      {
        path: 'lib/utils.ts',
        content: `export function cn(...classes: (string | undefined | null | false)[]): string {
  return classes.filter(Boolean).join(' ');
}

export function formatDate(date: Date | string): string {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}
`,
      },
    ];
  }

  private generateAPIClient(apis: any[]): { path: string; content: string } {
    const methods = apis.map((api) => {
      const methodName = api.method.toLowerCase();
      return `  async ${methodName}${this.toPascalCase(api.path.replace(/[^a-z]/gi, ''))}() {
    // TODO: Implement ${api.method} ${api.path}
    return fetch('/api${api.path}');
  }`;
    });

    return {
      path: 'lib/api.ts',
      content: `const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || '/api';

export class ApiClient {
  private baseUrl: string;

  constructor(baseUrl: string = API_BASE_URL) {
    this.baseUrl = baseUrl;
  }

${methods.join('\n\n')}
}

export const api = new ApiClient();
`,
    };
  }

  private generatePackageJson(): { path: string; content: string } {
    return {
      path: 'package.json',
      content: JSON.stringify(
        {
          name: 'omniforge-generated-app',
          version: '0.1.0',
          private: true,
          scripts: {
            dev: 'next dev',
            build: 'next build',
            start: 'next start',
            lint: 'next lint',
          },
          dependencies: {
            next: '14.0.4',
            react: '^18.2.0',
            'react-dom': '^18.2.0',
          },
          devDependencies: {
            '@types/node': '^20.10.0',
            '@types/react': '^18.2.45',
            '@types/react-dom': '^18.2.18',
            typescript: '^5.3.3',
            'tailwindcss': '^3.4.0',
            autoprefixer: '^10.4.16',
            postcss: '^8.4.32',
          },
        },
        null,
        2
      ),
    };
  }

  private generateNextConfig(): { path: string; content: string } {
    return {
      path: 'next.config.js',
      content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

module.exports = nextConfig;
`,
    };
  }

  private generateTailwindConfig(ui?: any): { path: string; content: string } {
    return {
      path: 'tailwind.config.js',
      content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '${ui?.primaryColor || '#3b82f6'}',
        },
      },
    },
  },
  plugins: [],
};
`,
    };
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }
}
