import { AppSpec, PageSpec, ComponentSpec, UIPreferences } from '@omniforge/shared';

const STYLE_PRESETS: Record<string, { nav: string; hero: string; card: string; cta: string; footer: string }> = {
  'minimal': { nav: 'bg-white border-b', hero: 'bg-gray-50', card: 'border border-gray-200', cta: 'bg-gray-900', footer: 'bg-gray-100' },
  'modern-saas': { nav: 'bg-white/80 backdrop-blur-sm border-b', hero: 'bg-gradient-to-br from-primary-500 to-primary-700', card: 'rounded-xl border shadow-sm', cta: 'bg-primary-600', footer: 'bg-gray-900' },
  'glassmorphism': { nav: 'bg-white/20 backdrop-blur-xl border-white/20', hero: 'bg-gradient-to-br from-violet-500/80 to-purple-700/80 backdrop-blur', card: 'bg-white/10 backdrop-blur border-white/20', cta: 'bg-white/20 backdrop-blur', footer: 'bg-black/20 backdrop-blur' },
  'neumorphism': { nav: 'bg-gray-100 shadow-inner', hero: 'bg-gray-100', card: 'bg-gray-100 shadow-[inset_2px_2px_4px_#fff,inset_-2px_-2px_4px_#ccc]', cta: 'bg-gray-100 shadow-lg', footer: 'bg-gray-200' },
  'bold-startup': { nav: 'bg-black text-white', hero: 'bg-black text-white', card: 'border-2 border-black', cta: 'bg-yellow-400 text-black', footer: 'bg-black text-white' },
  'luxury': { nav: 'bg-amber-50 border-amber-200', hero: 'bg-gradient-to-b from-amber-50 to-amber-100', card: 'border-amber-200 shadow-amber-100/50', cta: 'bg-amber-800 text-amber-50', footer: 'bg-amber-900 text-amber-200' },
  'playful': { nav: 'bg-pink-100', hero: 'bg-gradient-to-r from-pink-400 to-purple-400', card: 'rounded-2xl border-4 border-pink-300', cta: 'bg-green-400 text-white', footer: 'bg-purple-600 text-white' },
  'dark-first': { nav: 'bg-gray-900 border-gray-700', hero: 'bg-gray-900', card: 'bg-gray-800 border-gray-700', cta: 'bg-violet-600', footer: 'bg-black' },
  'material': { nav: 'shadow-md', hero: 'bg-primary-600', card: 'shadow-lg rounded', cta: 'bg-primary-700', footer: 'bg-gray-800' },
  'ios': { nav: 'bg-gray-100/80 backdrop-blur-xl', hero: 'bg-white', card: 'rounded-2xl shadow-sm', cta: 'bg-blue-500', footer: 'bg-gray-100' },
};

export class FrontendAgent {
  private huggingFaceService: any;
  private _uiPrefs: UIPreferences | undefined;

  constructor(huggingFaceService?: any) {
    this.huggingFaceService = huggingFaceService;
  }

  /**
   * Generates comprehensive Next.js frontend code with Hugging Face assistance
   */
  async generateFrontend(spec: AppSpec): Promise<{ files: Array<{ path: string; content: string }> }> {
    this._uiPrefs = spec.uiPreferences;
    const files: Array<{ path: string; content: string }> = [];

    // Generate layout (await is not needed here as it's synchronous)
    files.push(this.generateLayout());

    // Generate pages
    for (const page of spec.pages || []) {
      // Generate page component inline
      const pageContent = this.generatePageContent(page);
      files.push(this.generatePage(page, pageContent));
      files.push(this.generatePageMetadata(page));
    }

    // Generate shared components
    files.push(...this.generateSharedComponents());

    // Generate hooks
    files.push(...this.generateHooks());

    // Generate utilities
    files.push(...this.generateUtilities());

    // Generate API client
    files.push(this.generateAPIClient(spec.apis || []));

    // Generate package.json
    files.push(this.generatePackageJson());

    // Generate next.config.js
    files.push(this.generateNextConfig());

    // Generate tailwind.config.js
    files.push(this.generateTailwindConfig(spec.ui));

    return { files };
  }

  private generateLayout(): { path: string; content: string } {
    return {
      path: 'app/layout.tsx',
      content: `import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'OmniForge Generated App',
  description: 'Generated by OmniForge',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
`,
    };
  }

  private generatePageContent(page: PageSpec): string {
    const components = page.components || [];
    return components.map((c, i) => this.generateComponentCode(c, i)).join('\n        ');
  }

  private generatePage(page: PageSpec, content?: string): { path: string; content: string } {
    const componentName = this.toPascalCase(page.name);
    const components = page.components || [];

    // Use generated content if available, otherwise fallback
    if (content) {
      return {
        path: `app${page.path === '/' ? '' : page.path}/page.tsx`,
        content,
      };
    }

    return {
      path: `app${page.path === '/' ? '' : page.path}/page.tsx`,
      content: `'use client';

import { useEffect, useState } from 'react';

export default function ${componentName}Page() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // TODO: Fetch page data
    setLoading(false);
  }, []);

  if (loading) {
    return <div className="flex items-center justify-center min-h-screen">Loading...</div>;
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow-sm border-b">
        <div className="container mx-auto px-4 py-4">
          <h1 className="text-2xl font-bold text-gray-900">${page.name}</h1>
        </div>
      </header>
      <main className="container mx-auto px-4 py-8">
        ${components.map((c, i) => this.generateComponentCode(c, i)).join('\n        ')}
      </main>
    </div>
  );
}
`,
    };
  }

  private generatePageMetadata(page: PageSpec): { path: string; content: string } {
    return {
      path: `app${page.path === '/' ? '' : page.path}/metadata.ts`,
      content: `import { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${page.name}',
  description: '${page.name} page',
};
`,
    };
  }

  private getStylePreset() {
    const style = this._uiPrefs?.style || 'modern-saas';
    return STYLE_PRESETS[style] || STYLE_PRESETS['modern-saas'];
  }

  private getThemeClasses() {
    const theme = this._uiPrefs?.theme || 'light';
    const dark = theme === 'dark' || (theme === 'auto' && false);
    return dark
      ? { text: 'text-white', textMuted: 'text-gray-400', bg: 'bg-gray-900', border: 'border-gray-700' }
      : { text: 'text-gray-900', textMuted: 'text-gray-600', bg: 'bg-white', border: 'border-gray-200' };
  }

  private generateComponentCode(component: ComponentSpec, index: number): string {
    const type = (component.type || '').toLowerCase().replace(/\s/g, '');
    const props = component.props || {};
    const s = this.getStylePreset();
    const tc = this.getThemeClasses();

    const esc = (v: unknown) =>
      String(v ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, ' ');

    const children = component.children
      ?.map((c, i) => this.generateComponentCode(c, i))
      .join('\n        ') || '';

    switch (type) {
      case 'navbar':
      case 'nav':
      case 'header':
        return `<nav key="${index}" className="flex items-center justify-between px-6 py-4 ${s.nav} ${tc.border}">
          <span className="text-xl font-bold ${tc.text}">${esc(props.title || 'Brand')}</span>
          <button className="px-4 py-2 bg-primary-600 text-white rounded-lg font-medium hover:bg-primary-700 transition-colors">${esc(props.ctaLabel || 'Get Started')}</button>
        </nav>`;
      case 'hero':
        return `<section key="${index}" className="py-20 px-6 text-center ${s.hero}">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-4xl md:text-5xl font-bold mb-6 text-white">${esc(props.title || 'Build Something Amazing')}</h1>
            <p className="text-lg mb-8 text-white/90">${esc(props.subtitle || '')}</p>
            <button className="px-6 py-3 bg-white text-primary-600 rounded-lg font-semibold hover:bg-gray-100 transition-colors">${esc(props.ctaLabel || 'Get Started')}</button>
          </div>
        </section>`;
      case 'featuregrid':
      case 'features':
        return children
          ? `<section key="${index}" className="py-16 px-6"><h2 className="text-2xl font-bold text-center mb-8 ${tc.text}">${esc(props.title || 'Features')}</h2><div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
        ${children}
        </div></section>`
          : `<section key="${index}" className="py-16 px-6"><h2 className="text-2xl font-bold text-center mb-8 ${tc.text}">${esc(props.title || 'Features')}</h2><div className="max-w-6xl mx-auto grid gap-8" /></section>`;
      case 'featurecard':
      case 'feature_card':
        return `<div key="${index}" className="p-6 ${s.card} ${tc.bg}">
          <div className="text-3xl mb-3">${esc(props.icon || '✨')}</div>
          <h3 className="text-xl font-semibold mb-2 ${tc.text}">${esc(props.title || 'Feature')}</h3>
          <p className="${tc.textMuted}">${esc(props.description || '')}</p>
        </div>`;
      case 'cta':
      case 'calltoaction':
        return `<section key="${index}" className="py-16 px-6 ${s.cta} text-center">
          <h2 className="text-2xl font-bold text-white mb-4">${esc(props.title || 'Ready to get started?')}</h2>
          <button className="px-8 py-3 bg-white text-primary-600 rounded-lg font-semibold hover:bg-gray-100 transition-colors">${esc(props.buttonLabel || 'Get Started')}</button>
        </section>`;
      case 'footer':
        return `<footer key="${index}" className="py-8 px-6 ${s.footer} ${tc.textMuted} text-center">
          © ${new Date().getFullYear()} ${esc(props.brand || 'App')}
        </footer>`;
      default:
        return `<div key="${index}" className="mb-4">{/* ${component.type} */}</div>`;
    }
  }

  private generateSharedComponents(): Array<{ path: string; content: string }> {
    return [
      {
        path: 'components/ui/Button.tsx',
        content: `interface ButtonProps {
  children: React.ReactNode;
  onClick?: () => void;
  variant?: 'primary' | 'secondary' | 'outline';
  disabled?: boolean;
}

export function Button({ children, onClick, variant = 'primary', disabled }: ButtonProps) {
  const baseStyles = 'px-4 py-2 rounded-lg font-medium transition-colors';
  const variants = {
    primary: 'bg-blue-600 text-white hover:bg-blue-700',
    secondary: 'bg-gray-200 text-gray-900 hover:bg-gray-300',
    outline: 'border border-gray-300 text-gray-700 hover:bg-gray-50',
  };

  return (
    <button
      className={\`\${baseStyles} \${variants[variant]} \${disabled ? 'opacity-50 cursor-not-allowed' : ''}\`}
      onClick={onClick}
      disabled={disabled}
    >
      {children}
    </button>
  );
}
`,
      },
      {
        path: 'components/ui/Card.tsx',
        content: `interface CardProps {
  children: React.ReactNode;
  className?: string;
}

export function Card({ children, className = '' }: CardProps) {
  return (
    <div className={\`bg-white rounded-xl shadow-sm border border-gray-200 p-6 \${className}\`}>
      {children}
    </div>
  );
}
`,
      },
      {
        path: 'components/ui/Input.tsx',
        content: `interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
}

export function Input({ label, error, className = '', ...props }: InputProps) {
  return (
    <div className="w-full">
      {label && <label className="block text-sm font-medium text-gray-700 mb-1">{label}</label>}
      <input
        className={\`w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 \${error ? 'border-red-500' : 'border-gray-300'} \${className}\`}
        {...props}
      />
      {error && <p className="mt-1 text-sm text-red-600">{error}</p>}
    </div>
  );
}
`,
      },
    ];
  }

  private generateHooks(): Array<{ path: string; content: string }> {
    return [
      {
        path: 'hooks/useApi.ts',
        content: `import { useState, useEffect } from 'react';

export function useApi<T>(url: string) {
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch(url)
      .then((res) => res.json())
      .then((data) => {
        setData(data);
        setLoading(false);
      })
      .catch((err) => {
        setError(err.message);
        setLoading(false);
      });
  }, [url]);

  return { data, loading, error };
}
`,
      },
    ];
  }

  private generateUtilities(): Array<{ path: string; content: string }> {
    return [
      {
        path: 'lib/utils.ts',
        content: `export function cn(...classes: (string | undefined | null | false)[]): string {
  return classes.filter(Boolean).join(' ');
}

export function formatDate(date: Date | string): string {
  return new Date(date).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}
`,
      },
    ];
  }

  private generateAPIClient(apis: any[]): { path: string; content: string } {
    const methods = apis.map((api) => {
      const methodName = api.method.toLowerCase();
      return `  async ${methodName}${this.toPascalCase(api.path.replace(/[^a-z]/gi, ''))}() {
    // TODO: Implement ${api.method} ${api.path}
    return fetch('/api${api.path}');
  }`;
    });

    return {
      path: 'lib/api.ts',
      content: `const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || '/api';

export class ApiClient {
  private baseUrl: string;

  constructor(baseUrl: string = API_BASE_URL) {
    this.baseUrl = baseUrl;
  }

${methods.join('\n\n')}
}

export const api = new ApiClient();
`,
    };
  }

  private generatePackageJson(): { path: string; content: string } {
    return {
      path: 'package.json',
      content: JSON.stringify(
        {
          name: 'omniforge-generated-app',
          version: '0.1.0',
          private: true,
          scripts: {
            dev: 'next dev',
            build: 'next build',
            start: 'next start',
            lint: 'next lint',
          },
          dependencies: {
            next: '14.0.4',
            react: '^18.2.0',
            'react-dom': '^18.2.0',
          },
          devDependencies: {
            '@types/node': '^20.10.0',
            '@types/react': '^18.2.45',
            '@types/react-dom': '^18.2.18',
            typescript: '^5.3.3',
            'tailwindcss': '^3.4.0',
            autoprefixer: '^10.4.16',
            postcss: '^8.4.32',
          },
        },
        null,
        2
      ),
    };
  }

  private generateNextConfig(): { path: string; content: string } {
    return {
      path: 'next.config.js',
      content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

module.exports = nextConfig;
`,
    };
  }

  private generateTailwindConfig(ui?: any): { path: string; content: string } {
    return {
      path: 'tailwind.config.js',
      content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '${ui?.primaryColor || '#3b82f6'}',
        },
      },
    },
  },
  plugins: [],
};
`,
    };
  }

  private toPascalCase(str: string): string {
    return str
      .replace(/[^a-zA-Z0-9]/g, ' ')
      .split(' ')
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }
}
